name: Auto Assign Bump Issues
on:
   pull_request:
      types: [opened]

jobs:
   auto-assign:
      runs-on: ubuntu-latest

      steps:
         - name: Check if PR title starts with "Bump"
           uses: actions/github-script@v7
           with:
              script: |
                 const prTitle = context.payload.pull_request.title;
                 if (prTitle.startsWith('Bump')) {
                   return true;
                 }
                 return false;
           id: check_bump_pr

         - name: Assign the PR
           if: steps.check_bump_pr.outputs.result == 'true'
           uses: actions/github-script@v7
           with:
              script: |
                 const assignees = ['henri-tremblay'];
                 await github.rest.issues.addAssignees({
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   issue_number: context.issue.number,
                   assignees: assignees
                 });

         - name: Get open milestones
           if: steps.check_bump_pr.outputs.result == 'true'
           uses: actions/github-script@v7
           with:
              script: |
                 const { data: milestones } = await github.rest.issues.listMilestones({
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   state: 'open'
                 });

                 if (milestones.length === 0) {
                   core.setFailed('No open milestones found');
                 } else {
                   return milestones[0].number;
                 }

           id: get_open_milestone

         - name: Assign the PR to the milestone
           if: steps.get_open_milestone.outputs.result
           uses: actions/github-script@v7
           with:
              script: |
                 const milestoneNumber = parseInt("${{ steps.get_open_milestone.outputs.result }}", 10);

                 await github.rest.issues.update({
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   issue_number: context.issue.number,
                   milestone: milestoneNumber
                 });
